apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawi-server-deployment
  labels:
    app: tawi-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tawi-server-pod
  template:
    metadata:
      labels:
        app: tawi-server-pod
    spec:
      imagePullSecrets:
        - name: tawi-container-registry
      containers:
        - name: tawi-server
          image: registry.digitalocean.com/tawi-container-registry/tawi_server:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: tawi-prod-env-secrets
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata: 
  name: tawi-server-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80 # pod/container port
  selector:
    app: tawi-server-pod
