name: TAWI API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      DJANGO_SECRET_KEY: MyCoolAwe$omeS3cr3tKey!
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: 0.0.0.0,*
      DJANGO_PORT: 9000
      DJANGO_SUPERUSER_EMAIL: administrator@tawi.com
      DJANGO_SUPERUSER_USERNAME: administrator
      DJANGO_SUPERUSER_PASSWORD: MyAwesomeDBMan1Admin$$
      DB_IGNORE_SSL: true
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: MyCoolAwe$omeR00tPasswo0rd
      MYSQL_DATABASE: tawi_test_db
      MYSQL_USER: dbadministrator
      MYSQL_PASSWORD: MyKillerPa$$wo0rd

    services:
      mysql_db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${ env.MYSQL_ROOT_PASSWORD }
          MYSQL_DATABASE: ${ env.MYSQL_DATABASE }
          MYSQL_USER: ${ env.MYSQL_USER }
          MYSQL_PASSWORD: ${ env.MYSQL_PASSWORD }
        ports:
          - 3306:3306

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run Tests
      run: |
        python manage.py test
