name: Tawi Build
run-name: Build API and Push to DO Registry 🚀
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    uses: PeterKahenya/tawi/.github/workflows/test_api.yml@main
  build:
    runs-on: ubuntu-latest
    needs: test-api
    env:
      DJANGO_SECRET_KEY: MyCoolAwe$omeS3cr3tKey!
      K8S_CLUSTER_NAME: tawi-k8-cluster
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DO Registry with Short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      
      - name: Build tawi_api image
        run: |
          docker build \
          -t registry.digitalocean.com/tawi-container-registry/tawi_api:latest \
          -t registry.digitalocean.com/tawi-container-registry/tawi_api:${GITHUB_SHA::7} \
          api/
      
      - name: Build tawi_server image
        run: |
          docker build \
          -t registry.digitalocean.com/tawi-container-registry/tawi_server:latest \
          -t registry.digitalocean.com/tawi-container-registry/tawi_server:${GITHUB_SHA::7} \
          nginx/
      
      - name: Push Images
        run: | 
          docker push registry.digitalocean.com/tawi-container-registry/tawi_api --all-tags
          docker push registry.digitalocean.com/tawi-container-registry/tawi_server --all-tags

      - name: K8s cluster kubeconfig file with Short-lived credentials
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.K8S_CLUSTER_NAME }}
          
      - name: Update Deployment Images
        run: |
          kubectl set image deployment/tawi-api-deployment tawi-api=registry.digitalocean.com/tawi-container-registry/tawi_api:${GITHUB_SHA::7}
          kubectl set image deployment/tawi-server-deployment tawi-server=registry.digitalocean.com/tawi-container-registry/tawi_server:${GITHUB_SHA::7}

      - name: Wait for Rollout to finish
        run: |
          kubectl rollout status deployment/tawi-api-deployment
          kubectl rollout status deployment/tawi-server-deployment
          

