name: Tawi Build
run-name: Build API and Push to DO Registry 🚀
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    uses: PeterKahenya/tawi/.github/workflows/test_api.yml@main
  build:
    runs-on: ubuntu-latest
    needs: test-api
    env:
      K8S_CLUSTER_NAME: tawi-k8-cluster
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DO Registry with Short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      
      - name: Build tawi_api image
        run: |
          docker build \
          -t registry.digitalocean.com/tawi-container-registry/tawi_api:latest \
          -t registry.digitalocean.com/tawi-container-registry/tawi_api:${GITHUB_SHA::7} \
          api/
      
      - name: Build tawi_server image
        run: |
          docker build \
          -t registry.digitalocean.com/tawi-container-registry/tawi_server:latest \
          -t registry.digitalocean.com/tawi-container-registry/tawi_server:${GITHUB_SHA::7} \
          nginx/
      
      - name: Push Images
        run: | 
          docker push registry.digitalocean.com/tawi-container-registry/tawi_api --all-tags
          docker push registry.digitalocean.com/tawi-container-registry/tawi_server --all-tags

      - name: K8s cluster kubeconfig file with Short-lived credentials
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.K8S_CLUSTER_NAME }}

      - name: Update k8s secrets
        run: |
          cat << EOF >> ./.env.prod

          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG=0
          DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_PORT=${{ secrets.DJANGO_PORT }}
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DB_IGNORE_SSL=${{ secrets.DB_IGNORE_SSL }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          API_URL=${{ secrets.API_URL }}

          EOF

          kubectl delete secrets tawi-prod-env-secrets
          kubectl create secret generic tawi-prod-env-secrets --from-env-file ./.env.prod

      - name: Update Deployment Images
        run: |
          kubectl set image deployment/tawi-api-deployment tawi-api=registry.digitalocean.com/tawi-container-registry/tawi_api:${GITHUB_SHA::7}
          kubectl set image deployment/tawi-server-deployment tawi-server=registry.digitalocean.com/tawi-container-registry/tawi_server:${GITHUB_SHA::7}

      - name: Wait for Rollout to finish
        run: |
          kubectl rollout status deployment/tawi-api-deployment
          kubectl rollout status deployment/tawi-server-deployment
          

