name: Tawi Build
run-name: Build API and Push to DO Registry 🚀
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_api:
    uses: PeterKahenya/tawi/.github/workflows/test_api.yml@main
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: MyCoolAwe$omeS3cr3tKey!
    steps:
      - uses: actions/checkout@v3
