name: Tawi Test
run-name: Test API by @${{ github.actor }} 🚀
on:
  workflow_call:
  workflow_dispatch:

jobs:
  django_test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: MyCoolAwe$omeS3cr3tKey!
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: 0.0.0.0,*
      DJANGO_PORT: 9000
      DJANGO_SUPERUSER_EMAIL: administrator@tawi.com
      DJANGO_SUPERUSER_USERNAME: administrator
      DJANGO_SUPERUSER_PASSWORD: MyAwesomeDBMan1Admin$$
      DB_IGNORE_SSL: true
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: MyCoolAwe$omeR00tPasswo0rd
      MYSQL_DATABASE: tawi_test_db
      MYSQL_USER: dbadministrator
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: MyKillerPa$$wo0rd
    defaults:
      run:
        working-directory: ./api
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      mysql-db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${ env.MYSQL_ROOT_PASSWORD }
          MYSQL_DATABASE: ${ env.MYSQL_DATABASE }
          MYSQL_USER: ${ env.MYSQL_USER }
          MYSQL_PASSWORD: ${ env.MYSQL_PASSWORD }
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
  
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restart db service
        run: |
          journalctl -xeu mysql.service

      # systemctl status mysql.service
      # mysqld --validate-config
      # sudo /etc/init.d/mysql start
      #     mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      #     service mysql restart
          

      # - name: Test db database
      #   run: |
      #     mysql -u"${{ env.MYSQL_USER }}"" -p"${{ env.MYSQL_PASSWORD }}"" -e "SELECT 1;"

      - name: Run Tests
        run: |
          python manage.py test
